---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# landsimR

<!-- badges: start -->
<!-- badges: end -->

The package landsimR aims to create virtual landscapes ...

## Installation

You can install the development version of landsimR using devtools:

``` r
devtools::install_github('m-kucera/landsimR')
```

## Basic Virtual Landscape Creation


```{r example}
library(landsimR)
set.seed(1)
landscape <- create_landscape(c(100, 100), c(.1, .1, .05), c(.5, .1, .3))
```

Plot of `landscape`:

```{r plot-landscape, echo = FALSE, message = FALSE}
library(terra)
plot(rast(landscape))
```
Adding line features to `landscape`:

```{r add-lines}
landscape2 <- add_lines(landscape, c(1, .025), c(F, .025), c(3, 0))
plot(rast(landscape2), col = c('green', 'yellow', 'blue', 'orange', 'black', 'brown'))
```
